server:
  port: 8080

github:
  owner: "rmanna"
  org: "rmanna"
  files: "README.md,azure-pipeline.yaml,sonar-project.properties"
  basebranch: "develop"
  authorname: "Self-Service Automation"
  authoremail: "oldevops@openlane.com"
  commitmessage: "Initial Project Commit"
  token: "13b0268b109828397bf051216cd3a430d912be7a"